### ISSUE TITLE
KubeFed Controller doesn't remove overrides from FederatedDeployment when ReplicaSchedulingPreference is deleted

### ISSUE THREAD

**Issue by mvazquezc** [kubernetes-sigs/kubefed#1066]
**What happened**:

1. Created a FederatedDeployment with 1 replica on each cluster.
2. Created a basic ReplicaSchedulingPreference that defines 9 replicas distributed to "*" with a weight of 1
3. 3 replicas are placed on each cluster (FederatedDeployment overrides updated by KubeFed Controller)
4. ReplicaSchedulingPreference is deleted
5. FederatedDeployment overrides are not removed so 3 replicas are still placed on each cluster

If instead of removing the ReplicaSchedulingPreference you try to update it:

If you try to update the already existing ReplicaSchedulingPreference to a different type of scheduling like weighted scheduling, the former overrides are not modified, so changes are not applied.

**What you expected to happen**:
1. When ReplicaSchedulingPreference is deleted, FederatedDeployment overrides should be deleted
2. When ReplicaSchedulingPreference is updated, FederatedDeployment overrides should be updated accordingly

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a FederatedDeployment

```yaml
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedDeployment
metadata:
  name: reverse-words
spec:
  placement:
    clusters:
    - name: cluster1
    - name: cluster2
    - name: cluster3
  template:
    metadata:
      labels:
        name: reverse-words
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: reverse-words
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            name: reverse-words
          namespace: reverse-words
        spec:
          containers:
          - image: quay.io/mavazque/reversewords:latest
            imagePullPolicy: Always
            name: reverse-words
            ports:
            - containerPort: 8080
              name: reverse-words
              protocol: TCP
          restartPolicy: Always
```
2. Create a ReplicaSchedulingPreference

```yaml
apiVersion: scheduling.kubefed.k8s.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: reverse-words
spec:
  targetKind: FederatedDeployment
  totalReplicas: 9
  clusters:
    "*":
      weight: 1
```

3. Remove ReplicaSchedulingPreference
OR
4. Update ReplicaSchedulingPreference to

```yaml
apiVersion: scheduling.kubefed.k8s.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: reverse-words
spec:
  targetKind: FederatedDeployment
  totalReplicas: 20
  clusters:
    cluster1:
      weight: 1
    cluster2:
      weight: 2
    cluster3:
      weight: 3
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`) 1.13.4+838b4fa
- KubeFed version v0.1.0-rc4-dirty
- Scope of installation (namespaced or cluster) cluster
- Others

/kind bug
