### ISSUE TITLE
Reconcile() Error in ServiceDNS Controller is not logged. Document requirements for clusters for using ServiceDNS

### ISSUE THREAD

**Issue by dionysius** [kubernetes-sigs/kubefed#1112]
**What happened**:
My example federatedservice with servicedns doesn't get any status updates and thus not creating any dns records. [Track down see slack thread](https://kubernetes.slack.com/archives/C09R1PJR3/p1565960089172100?thread_ts=1565706060.154100&cid=C09R1PJR3). The initial error is basically issue #1031 - the resource will not be processed - which might be reasonable. But this requirement is nowhere documented and additionally, because the error in reconcile is nowhere logged - I was basically blind of the cause - and I was unable to track down the issue without looking into the code and adding some debug output.

```log
$ kubectl -n kube-federation-system logs kubefed-controller-manager-57b8cdbc95-9qft7 | grep "does not have Region or Zones Attributes"
<nothing>
```
```diff
@@ -305,9 +308,11 @@ func (c *Controller) reconcile(qualifiedName util.QualifiedName) util.Reconcilia
        // Iterate through all ready clusters and aggregate the service status for the key
        for _, cluster := range clusters {
                if cluster.Status.Region == nil || *cluster.Status.Region == "" || len(cluster.Status.Zones) == 0 {
+                       klog.Warningf("DEBUG: cluster.Status is not satisfied! Region: %v, Zones: %v", *cluster.Status.Region, cluster.Status.Zones)
                        runtime.HandleError(errors.Wrapf(err, "Cluster %q does not have Region or Zones Attributes", cluster.Name))
                        return util.StatusError
                }
+               klog.Warningf("DEBUG: cluster.Status is satisfied!")
                clusterDNS := dnsv1a1.ClusterDNS{
                        Cluster: cluster.Name,
                        Region:  *cluster.Status.Region,
```
```bash
W0816 14:43:30.090594       1 controller.go:301] DEBUG: c.serviceInformer.GetReadyClusters(): [0xc0003381a0 0xc000338000], <nil>
W0816 14:43:30.090698       1 controller.go:311] DEBUG: cluster.Status is not satisfied! Region: , Zones: []
```
```yaml
# $ kubectl get kubefedclusters.core.kubefed.io -n kube-federation-system cluster1 -o json | jq -r '.status'
{
  "conditions": [
    {
      "lastProbeTime": "2019-08-16T15:14:06Z",
      "lastTransitionTime": "2019-08-16T14:43:18Z",
      "message": "/healthz responded with ok",
      "reason": "ClusterReady",
      "status": "True",
      "type": "Ready"
    }
  ],
  "region": ""
}
```

**What you expected to happen**:
- The [error thrown in the controller](https://github.com/kubernetes-sigs/kubefed/blob/master/pkg/controller/servicedns/controller.go#L308) is actually output somewhere
- The requirement for Cluster `Region` and `Zone` is documented and there are some example commands to validate prerequisites. (and/or `kubefedctl join` has this check too).

**How to reproduce it (as minimally and precisely as possible)**:
- setup the clusters with kubeadm (they won't have any region or zone info)
- follow the user guide for multicluster service dns
- check the status of your servicednsrecord - it will stay empty

**Anything else we need to know?**:
Nodes need to be labeled with `failure-domain.beta.kubernetes.io/region` and `failure-domain.beta.kubernetes.io/zone`, [see Kubernetes documentation](https://kubernetes.io/docs/setup/best-practices/multiple-zones/#nodes-are-labeled)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.1
- KubeFed version: canary (v0.1.0-rc5-36-g96ea200e-dirty)
- Scope of installation (namespaced or cluster) cluster
- Others

/kind bug
