### ISSUE TITLE
Enable placement reference for placement policy

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#1116]
We are now combining the `placement` to federated resources as examples here https://github.com/kubernetes-sigs/kubefed/blob/master/example/sample1/federateddeployment.yaml#L24-L27 as follows:

```yaml
  placement:
    clusters:
      - name: cluster2
      - name: cluster1
    clusterSelector:
      matchLabels:
        foo: bar
```

The problem here is that I cannot share one `placement` for multiple federated resources, I need to create a separate `placement` spec for all of the federated resources even if there are multiple federated resources may share same placement policy.

How about re-consider if we can enable `placement` as a separate resource and add a field named as `placementReference` as follows? This can enable the `placement` can be shared by multiple federated resources.

```yaml
  placement:
    placementReference:
      name: placement1
    clusters:
      - name: cluster2
      - name: cluster1
    clusterSelector:
      matchLabels:
        foo: bar
```

FYI @kubernetes-sigs/kubefed-maintainers @marun
