### ISSUE TITLE
kubefedctl join - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by erloop** [kubernetes-sigs/kubefed#1123]
When I join cluster
`kubefedctl join  cluster1 --cluster-context cluster1 --host-cluster-context cluster1 --v=2`
I get error
``` Name:         clgm
Namespace:    kube-federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.kubefed.io/v1beta1
Kind:         KubeFedCluster
Metadata:
  Creation Timestamp:  2019-08-20T13:11:21Z
  Generation:          1
  Resource Version:    19254682
  Self Link:           /apis/core.kubefed.io/v1beta1/namespaces/kube-federation-system/kubefedclusters/cluster1
  UID:                 012e720f-c34c-11e9-ad1d-001a4a89fd0c
Spec:
  API Endpoint:  https://example.com/k8s/clusters/c-52hg
  Ca Bundle:     LS0tLS1CRUdJTiBDRVJUSUZ
  Secret Ref:
    Name:  cluster1-tkpqn
Status:
  Conditions:
    Last Probe Time:       2019-08-20T13:46:41Z
    Last Transition Time:  2019-08-20T13:11:22Z
    Message:               cluster is not reachable
    Reason:                ClusterNotReachable
    Status:                True
    Type:                  Offline
Events:
  Type     Reason                         Age                  From                       Message
  ----     ------                         ----                 ----                       -------
  Warning  RetrievingClusterHealthFailed  18s (x207 over 35m)  kubefedcluster-controller  Failed to retrieve health of the cluster: Get https://example.com/k8s/clusters/c-52hg/healthz?timeout=3s: x509: certificate signed by unknown authority
```

I use cluster 
`Rancher v2.2.5`

Certificate signed by **Go Daddy** 

My KUBECONFIG
```
apiVersion: v1
clusters:
- cluster:
    server: https://example.com/k8s/clusters/c-52hg
    name: cluster1
contexts:
- context:
    cluster: cluster1
    user: user-h6gwp
  name: cluster1
- name: user-h6gwp
  user:
    token: <<token>>

```

When run
`curl -u "<<token>>" https://example.com/k8s/clusters/c-52hg/healthz?timeout=3s`

receive
`ok`
