### ISSUE TITLE
enable api-resource on all member

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes-sigs/kubefed#1144]
With the 'UserGuid.md' follow, I'll enable api-resources in all member of federation clusters. And need deploy kubefed on other member?  Is too excute bellow?
```
[root@master2 ~]# ./scripts/deploy-kubefed.sh qiqisa/kubefed-mips64el:v0.1.0-rc6 master2
``` 
Or to excute bellow:
```
[root@master2 ~]# cd go/src/sigs.k8s.io/kubefed/charts/kubefed/templates/
[root@master2 templates]# kubectl apply -f  crds.yaml
```
When I deploy the sample  on the main cluster, get some errors:
```
[root@master1 example]# kubectl apply -R  -f sample1/
configmap/web-file unchanged
deployment.apps/nginx unchanged
federatedclusterrole.types.kubefed.io/test-clusterrole unchanged
federatedconfigmap.types.kubefed.io/test-configmap unchanged
federateddeployment.types.kubefed.io/test-deployment unchanged
federatedingress.types.kubefed.io/test-ingress unchanged
federatedjob.types.kubefed.io/test-job unchanged
federatednamespace.types.kubefed.io/test-namespace unchanged
federatedsecret.types.kubefed.io/test-secret unchanged
federatedservice.types.kubefed.io/test-service unchanged
federatedserviceaccount.types.kubefed.io/test-serviceaccount unchanged
namespace/test-namespace unchanged
unable to recognize "sample1/federatedclusterrolebinding.yaml": no matches for kind "FederatedClusterRoleBinding" in version "types.kubefed.io/v1beta1"

# there is no federateclusterrolebinding
[root@master1 example]# kubectl api-resources --api-group=types.kubefed.io
NAME                                SHORTNAMES   APIGROUP           NAMESPACED   KIND
federatedclusterroles                            types.kubefed.io   false        FederatedClusterRole
federatedconfigmaps                 fcm          types.kubefed.io   true         FederatedConfigMap
federateddeployments                fdeploy      types.kubefed.io   true         FederatedDeployment
federatedfederatedconfigmaps        ffcm         types.kubefed.io   true         FederatedFederatedConfigMap
federatedfederatedjobs                           types.kubefed.io   true         FederatedFederatedJob
federatedfederatednamespaces        ffns         types.kubefed.io   true         FederatedFederatedNamespace
federatedfederatedreplicasets       ffrs         types.kubefed.io   true         FederatedFederatedReplicaSet
federatedfederatedserviceaccounts   ffsa         types.kubefed.io   true         FederatedFederatedServiceAccount
federatedingresses                  fing         types.kubefed.io   true         FederatedIngress
federatedjobs                                    types.kubefed.io   true         FederatedJob
federatednamespaces                 fns          types.kubefed.io   true         FederatedNamespace
federatedreplicasets                frs          types.kubefed.io   true         FederatedReplicaSet
federatedsecrets                                 types.kubefed.io   true         FederatedSecret
federatedserviceaccounts            fsa          types.kubefed.io   true         FederatedServiceAccount
federatedservices                   fsvc         types.kubefed.io   true         FederatedService

```
- Verifying API type is installed on all member clusters

**Comment by marun** [comment]
- A KubeFed control plane needs to be deloyed to a single cluster, and all member clusters are joined to that control plane. There is no need to deploy multiple control planes or to install federated APIs in member clusters. 
- The yaml in `example/sample1` is intended for use with the userguide walkthrough, so the error you are seeing doesn't represent a problem. If there is a type that you want enabled for federation that is not provided by default, use `kubefedctl enable`.

**Comment by qiyongxiao** [comment]
@marun I use ```kubefedctl enable``` to enable this kind
```
[root@master1 sample1]# kubefedctl enable FederatedClusterRoleBinding
F0909 17:25:13.648292    2058 enable.go:110] Error: Unable to find api resource named "FederatedClusterRoleBinding".
```
### I deploy the sample, but there is no pod on running. And how to show the pod's running status?
```
[root@master1 sample1]# kubectl apply -f namespace.yaml  -f federatednamespace.yaml -f federateddeployment.yaml 
namespace/test-namespace unchanged
federatednamespace.types.kubefed.io/test-namespace unchanged
federateddeployment.types.kubefed.io/test-deployment unchanged
[root@master1 sample1]# kubectl get federateddeployments.types.kubefed.io -n test-namespace 
NAME              AGE
test-deployment   14m
[root@master1 sample1]# docker ps -a |grep nginx
```
### Here is the configurations:
```
[root@master1 sample1]# cat federateddeployment.yaml 
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: test-deployment
  namespace: test-namespace
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: qiqisa/nginx-mips64le
            name: nginx
            port: 80
  placement:
    clusters:
    - name: master2
    - name: master1
```

**Comment by marun** [comment]
> [root@master1 sample1]# kubefedctl enable FederatedClusterRoleBinding
> F0909 17:25:13.648292    2058 enable.go:110] Error: Unable to find api resource named "FederatedClusterRoleBinding".

`kubefedctl enable` enables federation of an existing type. If your intent was to federate `ClusterRoleBinding`, the invocation would be `kubefedctl enable ClusterRoleBinding`. This command would create the `FederatedClusterRoleBinding` type to allow declaring how a `ClusterRoleBinding` resource should appear in clusters registered to the KubeFed control plane. It would also create a `FederatedTypeConfig` to configure propagation of the federated type.

**Comment by qiyongxiao** [comment]
> > [root@master1 sample1]# kubefedctl enable FederatedClusterRoleBinding
> > F0909 17:25:13.648292    2058 enable.go:110] Error: Unable to find api resource named "FederatedClusterRoleBinding".
> 
> `kubefedctl enable` enables federation of an existing type. If your intent was to federate `ClusterRoleBinding`, the invocation would be `kubefedctl enable ClusterRoleBinding`. This command would create the `FederatedClusterRoleBinding` type to allow declaring how a `ClusterRoleBinding` resource should appear in clusters registered to the KubeFed control plane. It would also create a `FederatedTypeConfig` to configure propagation of the federated type.

### I was enabled it on kubefed control plane. But get error
```
[root@master1 sample1]# kubefedctl enable FederatedClusterRoleBinding
F0909 17:25:13.648292    2058 enable.go:110] Error: Unable to find api resource named "FederatedClusterRoleBinding".
```

**Comment by qiyongxiao** [comment]
@marun Deployed an nginx pod with FederatedDeployment, but can't get pod process. It could show the pod running status and get the process with ```docker ps |grep nginx``` ?
```
[root@master1 sample1]# kubectl apply -f namespace.yaml  -f federatednamespace.yaml -f federateddeployment.yaml 
namespace/test-namespace unchanged
federatednamespace.types.kubefed.io/test-namespace unchanged
federateddeployment.types.kubefed.io/test-deployment unchanged
[root@master1 sample1]# kubectl get federateddeployments.types.kubefed.io -n test-namespace 
NAME              AGE
test-deployment   14m
[root@master1 sample1]# docker ps -a |grep nginx
[root@master1 sample1]# 
```

**Comment by marun** [comment]
> I was enabled it on kubefed control plane. But get error
> ```
> [root@master1 sample1]# kubefedctl enable FederatedClusterRoleBinding
> F0909 17:25:13.648292    2058 enable.go:110] Error: Unable to find api resource named "FederatedClusterRoleBinding".
> ```

As per my original reply, it is not possible to enable types that do not exist. The error message is a clear indication that the API resource targeted by the command - `FederatedClusterRoleBinding`  - does not exist.  `FederatedClusterRoleBinding` would be created as a result of running `kubefedctl enable ClusterRoleBinding`.

**Comment by qiyongxiao** [comment]
@marun  This issues is not completion at now?
![image](https://user-images.githubusercontent.com/7349963/64540544-f86a3600-d352-11e9-815c-62ecff3fcc73.png)
![image](https://user-images.githubusercontent.com/7349963/64540716-30717900-d353-11e9-8a36-fc096f88ba85.png)

**Comment by marun** [comment]
@qinpingli Have you had an opportunity to review the userguide? It includes a [walkthrough](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#verify-your-deployment-is-working) of how to check if your deployment is working. It also documents how to interpret [propagation status](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#propagation-status) and otherwise [troubleshoot](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#troubleshooting) common problems.

**Comment by qinpingli** [comment]
@marun sure

**Comment by marun** [comment]
@qinpingli My apologies! I accidentally typed your name instead of @qiyongxiao.

**Comment by qinpingli** [comment]
> @qinpingli My apologies! I accidentally typed your name instead of @qiyongxiao.

@marun Never mind, ^_^.

**Comment by qiyongxiao** [comment]
@marun  Thank you very much for  your patients. Is only a problem with clusterOverrides.
Here is some configuration for my federateddeployment
```
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: test-deployment
  namespace: test-namespace
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: nginx
            name: nginx
  placement:
    clusters:
    - name: master1
    - name: devel
  overrides:
  - clusterName: devel
    clusterOverrides:
    - path: "/spec/replicas"
      value: 1
    - path: "/spec/template/spec/containers/0/image"
      value: "nginx:1.17.0-alpine"
    - path: spec.template/spec/containers/0/name
      value: nginx-alpine
    - path: "/metadata/annotations"
      op: "add"
      value:
        foo: bar 
```
For the first  to excute ``kubectl apply -f  federateddp.yaml``` on KubeFed control plane, with the master1 running nginx pod, image is nginx:latest.  With the devel running nginx pod, image is nginx:1.17.0-alpine.
When changed  the value of "/spec/replicas/" to 4, and then reexcute ```kubectl apply -f federateddp.yaml```, the cluster of devel's nginx pod is still 1, don't autoscale to 4.
