### ISSUE TITLE
Federated ingress is not working 

### ISSUE THREAD

**Issue by boopathykpm** [kubernetes-sigs/kubefed#1151]
I'm trying to create a federated ingress and I'm following the steps provided in https://github.com/kubernetes-sigs/kubefed/blob/master/docs/ingressdns-with-externaldns.md

I have installed the ExternalDNS with the following args to create the CRDs and also installed the ExternalDNS with RBAC enabled, then placed the ingress controller under `kube-system` namespace.

I tried to create the Federated ingress object under the namespace `test-namespace` which is federated. According to the document when the `IngressDNSRecord` is placed, it should be watched by the `DNSEndpoint` to create the domain, but I couldn't see such resource is created. 

I had added annotations to the Federated Ingress controller to link the ingress object to the Ingress controller which I had installed, but weirdly the controller is not able to pick the object created. 
`kops version`

`Version 1.13.0`

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

```
apiVersion: types.kubefed.io/v1beta1
kind: FederatedIngress
metadata:
  name: test-ingress
  namespace: test-namespace
  annotations:
      kubernetes.io/ingress.class: public
spec:
  template:
    spec:
      rules:
      - host: ingress.coda.run
        http:
          paths:
          - backend:
              serviceName: test-service
              servicePort: 80
  placement:
    clusters:
    - name: fed.coda.run
    - name: fed-one.coda.run
```
I see the ingress is created, but the Address column is empty, the Nginx controller is not able to identify the resource which is created. 

Any thoughts on this failure? 

/triage support
/kind bug
