### ISSUE TITLE
Error while joining cluster to federation pane

### ISSUE THREAD

**Issue by caueasantos** [kubernetes-sigs/kubefed#1176]
**What happened**:

`kubefedctl join gke-southamerica-east1-b --cluster-context gke-southamerica-east1-b \
    --host-cluster-context gke-southamerica-east1-a --v=2`

Error while joining cluster to federation plane:

`[F0115 13:34:19.313173  127748 join.go:126] Error: Error retrieving KubeFedConfig "kube-federation-system/kubefed": no matches for kind "KubeFedConfig" in version "core.kubefed.io/v1beta1"`

**What you expected to happen**:

The cluster should have joined successfully

**How to reproduce it (as minimally and precisely as possible)**:

1. KubeFed installation
2. GKE fresh installation (Twice)
    > Location type: Zonal + Using southamerica-east1-a and southamerica-east1-b
    > Networking: VPC-native disabled + Using private vpc and subnet
3. RBAC Workaround
   > Granted current Google Cloud Identity the cluster-admin role for each cluster
4. Helm Chart Installation
   > Configured RBAC for helm
   > Helm chart deployed
`helm-2.16 install kubefed-charts/federation-v2 --name kubefed --namespace kube-federation-system --kube-context gke-southamerica-east1-a`
   > All pods running

**Environment**:
- Kubernetes version (use `kubectl version`)
`Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}`
- KubeFed version
`kubefedctl version: version.Info{Version:"v0.1.0-rc6", GitCommit:"7586b42f4f477f1912caf28287fa2e0a7f68f407", GitTreeState:"clean", BuildDate:"2019-08-17T03:55:05Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`
- Scope of installation (namespaced or cluster)
`Cluster`
- Others

/kind bug

**Comment by hectorj2f** [comment]
@caueasantos The error means you're missing the kubefed configuration in the cluster, so I assume you won't get anything when running `kubectl get kubefedconfig  -A`. You should get something like:

```
apiVersion: core.kubefed.io/v1beta1
kind: KubeFedConfig
metadata:
  name: kubefed
spec:
  clusterHealthCheck:
    failureThreshold: 3
    period: 10s
    successThreshold: 1
    timeout: 3s
  controllerDuration:
    availableDelay: 20s
    unavailableDelay: 60s
  featureGates:
  - configuration: Enabled
    name: PushReconciler
  - configuration: Disabled
    name: SchedulerPreferences
  - configuration: Disabled
    name: CrossClusterServiceDiscovery
  - configuration: Enabled
    name: FederatedIngress
  leaderElect:
    leaseDuration: 15s
    renewDeadline: 10s
    resourceLock: configmaps
    retryPeriod: 5s
  scope: Cluster
  syncController:
    adoptResources: Enabled
```
If you didn't I assume the installation isn't correct or any of the kubefed pods are failing.
