### ISSUE TITLE
fed enable fails on duplicate names

### ISSUE THREAD

**Issue by armstrongli** [kubernetes-sigs/kubefed#1185]
**What happened**:
There are multiple CRDs/k8s resources created in k8s cluster with same name, and different groups. kubefedctl enable command fails because of the resource already federated. error message is
```
Federation is already enabled for xxxx with federated type xxxx. Changing the federated type to xxxx is not supported.
```

**What you expected to happen**:
All the resources with same name but different groups are enabled on federation

**How to reproduce it (as minimally and precisely as possible)**:
1. create 2 CRDs with same name and different groups. e.g.
```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: computenodes.foo.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      This is the description part
    name: Age
    type: date
  group: foo.io
  names:
    kind: ComputeNode
    listKind: ComputeNodeList
    plural: computenodes
    singular: computenode
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: computenodes.bar.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      This is the description part
    name: Age
    type: date
  group: bar.io
  names:
    kind: ComputeNode
    listKind: ComputeNodeList
    plural: computenodes
    singular: computenode
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
```

2. run kubefedctl commands to enable fed
```
kubectlfed enable computenodes.foo.io
kubectlfed enable computenodes.bar.io
```

**Anything else we need to know?**:
The code here is using federated type instead of origin type meta and loses part of the group information. then there is another CRD created with same name for resource
```go
func federatedTypeCRD(typeConfig typeconfig.Interface, accessor schemaAccessor, shortNames []string) *apiextv1b1.CustomResourceDefinition {
	templateSchema := accessor.templateSchema()
	schema := federatedTypeValidationSchema(templateSchema)
	return CrdForAPIResource(typeConfig.GetFederatedType(), schema, shortNames)
}
// the apiResoure is the federated resource, which already loses the origin group information.
func CrdForAPIResource(apiResource metav1.APIResource,....){
...
	return &apiextv1b1.CustomResourceDefinition{
...
		ObjectMeta: metav1.ObjectMeta{
			Name: typeconfig.GroupQualifiedName(apiResource),
		},
...
}

...
// here the name is federeatedxxx.types.kubefed.io
func GroupQualifiedName(apiResource metav1.APIResource) string {
	if len(apiResource.Group) == 0 {
		return apiResource.Name
	}
	return fmt.Sprintf("%s.%s", apiResource.Name, apiResource.Group)
}
```

**Environment**:
- Kubernetes version (use `kubectl version`): any version
- KubeFed version: on fed commit 02124cebf761322c889ebc53a933b08db02ad0ef 

/kind bug
