### ISSUE TITLE
Annotations are not federated

### ISSUE THREAD

**Issue by makkes** [kubernetes-sigs/kubefed#1215]
**What happened**:
Annotations in the `spec.template.metadata.annotations` part of federated resources are left out of federation.

**What you expected to happen**:
Annotations are propagated to the target resources.

**How to reproduce it (as minimally and precisely as possible)**:
Create a `FederatedConfigMap` on the management cluster:
```

apiVersion: types.kubefed.io/v1beta1
kind: FederatedConfigMap
metadata:
  name: makkes
spec:
  placement:
    clusters:
      - name: my-cluster
  template:
    metadata:
      labels:
        a: b
      annotations:
        c: d
    data:
      e: f
```
If there's a kubefed cluster named `my-cluster`, then kubefed correctly creates a `ConfigMap` on it but leaves out the annotations, even though it includes the labels.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.4
- KubeFed version: v0.2.0-alpha.1
- Scope of installation (namespaced or cluster)
- Others

/kind bug
