### ISSUE TITLE
overrides `op: add` seems not to work as expected for array values

### ISSUE THREAD

**Issue by ArchangelX360** [kubernetes-sigs/kubefed#1224]
**What happened**:

Let say I have:
```
spec:
  template:
    spec:
      template:
        spec:
          initContainers:
            - name: myinitcontainer
              args:
                - --logtostderr
```

Adding an override on an array key using `op: add`:

```
spec:
  overrides:
    - clusterName: mycluster
      clusterOverrides:
        - path: "/spec/template/spec/initContainers/0/args"
          op: add
          value:
            - --init
  template:
    spec:
      template:
        spec:
          initContainers:
            - name: myinitcontainer
              args:
                - --logtostderr
```

Created this object in `mycluster`:
```
spec:
    initContainers:
      - name: myinitcontainer
         args:
          - --init
```

**What you expected to happen**:

Merging the two arguments in the array, thus creating this object in `mycluster` instead:
```
spec:
    initContainers:
      - name: myinitcontainer
         args:
          - --init
          - --logtostderr
```

**How to reproduce it (as minimally and precisely as possible)**:

Apply the earlier described manifests.

**Anything else we need to know?**:

I don't think so, if anything missing, please comment :).

**Environment**:
- KubeFed version: `v0.3.0`

/kind bug

**Comment by xunpan** [comment]
@ArchangelX360 
It seems you did not follow the convention of https://tools.ietf.org/html/rfc6902#page-12
Please have another try to make path as below.
```
spec:
  overrides:
    - clusterName: mycluster
      clusterOverrides:
        - path: "/spec/template/spec/initContainers/0/args/0"
          op: add
          value:
            - --init
```

**Comment by ArchangelX360** [comment]
Oh I see, you meant:

```
spec:
  overrides:
    - clusterName: mycluster
      clusterOverrides:
        - path: "/spec/template/spec/initContainers/0/args/0"
          op: add
          value: --init
```

This works, thanks, I'll PR to add this to the override documentation to avoid future user's confusion.
