### ISSUE TITLE
Federated workloads' status is not updated with availableReplicas/readyReplicas

### ISSUE THREAD

**Issue by pacoxu** [kubernetes-sigs/kubefed#1240]
**What would you like to be added**:

Current status of FederatedDeployment
```
  status:
    clusters:
    - name: paco81
    - name: cluster0
    conditions:
    - lastTransitionTime: "2020-06-30T02:23:45Z"
      lastUpdateTime: "2020-06-30T02:42:22Z"
      status: "True"
      type: Propagation
    observedGeneration: 2
```
Deployment status
```
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-06-28T08:54:27Z"
      lastUpdateTime: "2020-06-28T08:54:36Z"
      message: ReplicaSet "python2-5qnzb-deployment-67ddd6c4b6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-06-28T10:13:23Z"
      lastUpdateTime: "2020-06-28T10:13:23Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
```

The expected status of federated deployment is something like.
```
  status:
    clusters:
    - name: paco81
      availableReplicas: 1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
    - name: cluster0
      availableReplicas: 1
      observedGeneration: 1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
    conditions:
    - lastTransitionTime: "2020-06-30T02:23:45Z"
      lastUpdateTime: "2020-06-30T02:42:22Z"
      status: "True"
      type: Propagation
    observedGeneration: 2
```

**Why is this needed**:
In federated resource aspect, we can see READY instances number and available instances numbers like deployment. 
```
[root@dce-10-7-177-8 .kube]# kubectl get deployment
NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
cloudevents-go-7nvpc-deployment   1/1     1            1           23h
dao-2048-dao-2048                 1/1     1            1           24h
```

For workloads like deployment/replicasets/statefulsets/daemonset, the status of each cluster would be shown in federated instances.

/kind feature
