### ISSUE TITLE
it's pretty good to add a detailed explanation of rsp

### ISSUE THREAD

**Issue by stevenshuang** [kubernetes-sigs/kubefed#1295]
**What happened**:
Tried `rsp` in federation cluster, when `rebalance` set as `true`, a pod in cluster2 can not be scheduled for a long, but cluster1 also does't create a new pod!
rsp settings are as follows:
```
apiVersion: scheduling.kubefed.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: nginx-onrfd
  namespace: fhpa
spec:
  clusters:
    cluster1:
      maxReplicas: 1
      minReplicas: 1
      weight: 1
    cluster2:
      maxReplicas: 5
      minReplicas: 1
      weight: 10
  rebalance: true
  targetKind: FederatedDeployment
  totalReplicas: 6
```
when i set `cluster1.maxReplicas=2`, after a while,  cluster1 creates a new pod. Whether `rebalance` is limited to `maxReplicas`?
**What you expected to happen**:
Maybe we should add a detailed explanation for `rsp` in doc.  Sometimes the allocation result is a bit confusing.

**Anything else we need to know?**:
 I have read the source code of algorithm and have some understanding of distribution.

/kind bug
