### ISSUE TITLE
empty spec in dnsendpoint  and status:     observedGeneration: 1

### ISSUE THREAD

**Issue by Reminisd** [kubernetes-sigs/kubefed#1316]
# question
![image](https://user-images.githubusercontent.com/39513283/98891824-f7461300-24d9-11eb-9979-1bbd2fe05995.png)
# external
        - --source=crd
        - --source=service
        - --crd-source-apiversion=multiclusterdns.kubefed.io/v1alpha1
        - --crd-source-kind=DNSEndpoint
        - --registry=txt
        - --provider=coredns
        - --log-level=debug # debug only
external logs
![image](https://user-images.githubusercontent.com/39513283/98891935-31afb000-24da-11eb-83a0-1a4700dc6e9d.png)
![image](https://user-images.githubusercontent.com/39513283/98891974-43915300-24da-11eb-93d4-fee38b9d0561.png)

labels 
![image](https://user-images.githubusercontent.com/39513283/98892048-6c194d00-24da-11eb-9259-c2f02671f698.png)

my Loadbalancer:
``` apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - xxxxxx-xxxxxxx
```

**Comment by Reminisd** [comment]
```
apiVersion: multiclusterdns.kubefed.io/v1alpha1
kind: Domain
metadata:
  # Corresponds to <federation> in the resource records.
  name: test-domain
  # The namespace running kubefed-controller-manager.
  namespace: kube-federation-system
# The domain/subdomain that is setup in your external-dns provider.
domain: your.domain.name
---
apiVersion: multiclusterdns.kubefed.io/v1alpha1
kind: ServiceDNSRecord
metadata:
  # The name of the sample service.
  name: test-service
  # The namespace of the sample deployment/service.
  namespace: test-namespace
spec:
  # The name of the corresponding `Domain`.
  domainRef: test-domain
  recordTTL: 300
```
