### ISSUE TITLE
Support DeleteOptions when deleting resources in member clusters

### ISSUE THREAD

**Issue by RolandMa1986** [kubernetes-sigs/kubefed#1348]
**What would you like to be added**:
Support DeleteOptions when deleting resources in member clusters.

**Why is this needed**:
DeleteOptions may be provided when deleting an object with kube-apiserver, such as GracePeriodSeconds and PropagationPolicy. This is extremely useful when the user wants to control the lifecycle of the federated resources as same as the Kubernetes's way.
ref: [DeleteOptions](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/delete-options/)

/kind feature

**Comment by RolandMa1986** [comment]
**User Story**
[KubeSphere](https://kubesphere.io/) is a tailored Kubernetes platform for hybrid multi-cloud. It providers an integrated multi-tenant and multi-cluster management solution. Kubefed is used to manage Multi-tenancy resources and workloads crossing clusters. Each workspace(a tenant) may contain one or more namespaces, which are owned by the workspace. When the workspace is being deleted, all the namespaces would be [GC](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/) too. But sometimes the admin doesn't want the namespaces to be deleted with workspace together, just leave them as orphan namespaces. 

In a single cluster, the propagationPolicy field on the deleteOptions is set to "Orphan", so we can stop the GC. However, In Multi-Clusters, the workspace's lifecycle is controlled by the federated workspace, currently, we can't apply the same deleteOptions as same a single cluster.

**DeleteOptions Annotation**

To apply the DeleteOptions while deleting the resources in the member cluster, a new annotation `kubefed.io/deleteoptions` is needed, which could be a JSON string of the [DeleteOptions](https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L492) type.

```yaml
apiVersion: types.kubefed.io/v1beta1
kind: Federated <type>
metadata:
  annotations:
    kubefed.io/deleteoptions: '{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Orphan"}'
  name: <name>
spec:
  placement:
    clusters:
    - name: host
  template:
    ...
```
Or

```bash
kubectl patch <federated type> <name> \
    --type=merge -p '{"metadata": {"annotations": {"kubefed.io/deleteoptions": "{\"kind\":\"DeleteOptions\",\"apiVersion\":\"v1\",\"propagationPolicy\":\"Orphan\"}"}}}'
```
