### ISSUE TITLE
unknown field "clusterMonitorPeriod" in io.kubefed.core.v1beta1.KubeFedConfig.spec.controllerDuration

### ISSUE THREAD

**Issue by luoMonkeyKing** [kubernetes-sigs/kubefed#1397]
**What happened**:
I want to verify the Multicluster Service DNS function. When I manually enable the function, I get an error when I execute kubectl apply -f kubefedconfig.yaml

error: error validating "kubefedconfig.yaml": error validating data: ValidationError(KubeFedConfig.spec.controllerDuration): unknown field "clusterMonitorPeriod" in io.kubefed.core.v1beta1.KubeFedConfig.spec.controllerDuration; if you choose to ignore these errors, turn validation off with --validate=false

### kubefedconfig.yaml：
```
apiVersion: core.kubefed.io/v1beta1
kind: KubeFedConfig
metadata:
  name: kubefed
  namespace: kube-federation-system
spec:
  scope: Cluster
  controllerDuration:
    availableDelay: 20s
    unavailableDelay: 60s
    clusterMonitorPeriod: 40s
  leaderElect:
    leaseDuration: 15s
    renewDeadline: 10s
    retryPeriod: 5s
    resourceLock: configmaps
  featureGates:
  - name: PushReconciler
    configuration: "Enabled"
  - name: RawResourceStatusCollection
    configuration: "Enabled"
  - name: SchedulerPreferences
    configuration: "Enabled"
  - name: CrossClusterServiceDiscovery
    configuration: "Enabled"
  - name: FederatedIngress
    configuration: "Enabled"

```
**Environment**:
- Kubernetes version (use `kubectl version`)
  v1.17.4
- KubeFed version
  v0.6.1
- Scope of installation (namespaced or cluster)
