### ISSUE TITLE
Replace map in ReplicaSchedulingPreference with named array

### ISSUE THREAD

**Issue by draveness** [kubernetes-sigs/kubefed#1402]
**What would you like to be added**:

```yaml
apiVersion: scheduling.kubefed.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: test-deployment
  namespace: test-ns
spec:
  targetKind: FederatedDeployment
  totalReplicas: 9
  clusters:
    - name: A
      weight: 1
    - name: B
      weight: 2
```

**Why is this needed**:

+ Kubernetes API is really bad at hash supporting, named array is more common in kubernetes API, and we should replace the map with a named array

/kind feature
