### ISSUE TITLE
Specify namespace in placement

### ISSUE THREAD

**Issue by gprossliner** [kubernetes-sigs/kubefed#1406]
**What would you like to be added**:
Allow kubefed to replicate between objects to a specific namespace, different from the master namespace.

**Why is this needed**:

I evaluate to use kubefed to be used to implement a multicluster Management tool. 
On the manager cluster, there is a namespace for each cluster like „dev“ or „prod“.
On the managed cluster, there is a corresponding namespace.
It is desirable that the namespace in all managed clusters are the same, like mgm-system. Basically it would want to specify the following in the api:

```yaml

apiVersion: types.kubefed.io/v1beta1
kind: FederatedNamespace
metadata:
  name: dev
  namespace: dev
spec:
  placement:
    clusters:
    - name: dev
      namespace: mgm-system
```

/kind feature
