### ISSUE TITLE
k3d instructions

### ISSUE THREAD

**Issue by OneCricketeer** [kubernetes-sigs/kubefed#1412]
**What would you like to be added**:

`k3d` kubefed scripts

**Why is this needed**:

`k3d` is similar to `kind`, but requires less resources

/kind feature

**Comment by OneCricketeer** [comment]
I _think_ I managed to get it working with the following 

ctrl.yml

```yml
apiVersion: k3d.io/v1alpha2
kind: Simple
image: docker.io/rancher/k3s:v1.19.10-k3s1
servers: 1
agents: 0  # only create master node on kubefed control plane
# ports:
#   - port: 0.0.0.0:8080:80
#     nodeFilters:
#       - agent[0]
#   - port: 0.0.0.0:8443:443
#     nodeFilters:
#       - agent[0]
#   - port: 0.0.0.0:5053:53/udp
#     nodeFilters:
#       - agent[0]
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: true
    disableImageVolume: true
  k3s:
    extraServerArgs:
      - "--no-deploy=traefik,servicelb,metrics-server"
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
```

worker.yml

```yml
apiVersion: k3d.io/v1alpha2
kind: Simple
image: docker.io/rancher/k3s:v1.19.10-k3s1
servers: 1
agents: 1
# ports:
#   - port: 0.0.0.0:9080:80
#     nodeFilters:
#       - agent[0]
#   - port: 0.0.0.0:9443:443
#     nodeFilters:
#       - agent[0]
#   - port: 0.0.0.0:5054:53/udp
#     nodeFilters:
#       - agent[0]
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: true
    disableImageVolume: true
  k3s:
    extraServerArgs:
      - "--no-deploy=traefik,servicelb,metrics-server"
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
```

With these steps

```sh
docker network create k3d-bridge

k3d cluster create ctrl --config=./resources/ctrl.yml --network k3d-bridge
helm --namespace kube-federation-system upgrade -i kubefed kubefed-charts/kubefed --create-namespace

k3d cluster create worker --config=./resources/worker.yml --network k3d-bridge
helm --namespace kube-federation-system upgrade -i kubefed kubefed-charts/kubefed --create-namespace

kubectl config use-context k3d-ctrl

kubefedctl join k3d-ctrl --cluster-context k3d-ctrl \
    --host-cluster-context k3d-ctrl --v=2
kubefedctl join k3d-worker --cluster-context k3d-worker \
    --host-cluster-context k3d-ctrl --v=2
```

Since I'm on a Mac, I [found the `kind` patch script in `scripts/`](https://github.com/kubernetes-sigs/kubefed/blob/master/scripts/fix-joined-kind-clusters.sh), and changed one line for `k3d`, and ran that 

```sh
IP_ADDR="$(docker inspect -f "${INSPECT_PATH}" "${cluster}-server-0")"
```

Now I have 

```sh
$ kubectl -n kube-federation-system get kubefedclusters
NAME         AGE     READY
k3d-worker   7m3s    True
k3d-ctrl     7m14s   True
```

And I verified the `FederatedConfigMap` example in the README worked...

```sh
$  kubectl -n federate-me describe fcm my-cm
...
Events:
  Type     Reason                 Age   From                           Message
  ----     ------                 ----  ----                           -------
  Normal   CreateInCluster        82s   federatedconfigmap-controller  Creating ConfigMap "federate-me/my-cm" in cluster "k3d-ctrl"
  Warning  CreateInClusterFailed  82s   federatedconfigmap-controller  Failed to create ConfigMap "federate-me/my-cm" in cluster "k3d-ctrl": An update will be attempted instead of a creation due to an existing resource
  Normal   CreateInCluster        81s   federatedconfigmap-controller  Creating ConfigMap "federate-me/my-cm" in cluster "k3d-worker"
  Normal   UpdateInCluster        81s   federatedconfigmap-controller  Updating ConfigMap "federate-me/my-cm" in cluster "k3d-ctrl"
```

---
 
Could run through the same, and tell me if I missed anything? If not, I can work on submitting docs/scripts, and maybe update the README to use `deploy.k3d` instead of `deploy.kind`??
