### ISSUE TITLE
templates field missing for istiooperator crds

### ISSUE THREAD

**Issue by yalctay93** [kubernetes-sigs/kubefed#1418]
**What happened**:

We are using kubefed version 0.7.0 as well as the kubefedctl in version 0.7.0
In our cluster, we are using the following istiooperator crd:

istiooperator crd version 1.10.0
```yaml
# SYNC WITH manifests/charts/istio-operator/templates
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.install.istio.io
  labels:
    release: istio
spec:
  conversion:
    strategy: None
  group: install.istio.io
  names:
    kind: IstioOperator
    listKind: IstioOperatorList
    plural: istiooperators
    singular: istiooperator
    shortNames:
    - iop
    - io
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Istio control plane revision
      jsonPath: .spec.revision
      name: Revision
      type: string
    - description: IOP current state
      jsonPath: .status.status
      name: Status
      type: string
    - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    subresources:
      status: {}
    name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
---
```

When we use the following command ```kubefedctl enable istiooperator``` the federatedIstioOperator crd is created without the "template" field. This leads to federatedIstioOperator creations that will always miss template configurations.

When deploying the istiooperator crd version 1.9.0 the template field is created with no issues:

```yaml
# SYNC WITH manifests/charts/istio-operator/templates
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.install.istio.io
  labels:
    release: istio
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.revision
    description: Istio control plane revision
    name: Revision
    type: string
  - JSONPath: .status.status
    description: IOP current state
    type: string
    name: Status
  - JSONPath: .metadata.creationTimestamp
    description: 'CreationTimestamp is a timestamp representing the server time when
      this object was created. It is not guaranteed to be set in happens-before order
      across separate operations. Clients may not set this value. It is represented
      in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
      lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
    name: Age
    type: date
  group: install.istio.io
  names:
    kind: IstioOperator
    plural: istiooperators
    singular: istiooperator
    shortNames:
    - iop
    - io
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        spec:
          description: 'Specification of the desired state of the istio control plane resource.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          type: object
        status:
          description: 'Status describes each of istio control plane component status at the current time.
            0 means NONE, 1 means UPDATING, 2 means HEALTHY, 3 means ERROR, 4 means RECONCILING.
            More info: https://github.com/istio/api/blob/master/operator/v1alpha1/istio.operator.v1alpha1.pb.html &
            https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
```

You should be able to reproduce this on any cluster. Right now, due to this we cannot update to istio version 1.10.0 because the federated component is created faulty in my oinion.

**What you expected to happen**:

template field should be included in the federatedIstioOperator

**How to reproduce it (as minimally and precisely as possible)**:

 1. deploy istiooperator crds for 1.9.0 use ```kubefedctl enable istiooperator``` command
 2. use following command to check if template field is created: ```kubectl get crd federatedistiooperators.types.kubefed.io -oyaml |grep template```

remove the crd again and the federatedIstioOperator crd aswell (also the federatedTypeConfig) e.g: 
```kubefedctl disable istiooperators.install.istio.io --delete-crd```
```kubectl delete crd istiooperators.install.istio.io```

afterwards deploy the istiooperator crd version 1.10.0
and do the same steps as above. The template field should be missing now.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`) 1.20.x
- KubeFed version 0.7.0
- Scope of installation (namespaced or cluster) cluster

/kind bug
