### ISSUE TITLE
Introduce overrideParams for Overrides 

### ISSUE THREAD

**Issue by qmhu** [kubernetes-sigs/kubefed#1434]
**What would you like to be added**:
How about support parameters during the override part. 

introduce new configuration part in override:
````
overrideParams:
- clusterName: your-cluster
  clusterParameters:
  - name: imageRegistry
    valurFrom:
      configMapKeyRef:
        name: ClusterRegistryInfo
        path: info.imageRegistry
````
support yaml template in federation deployment:

````
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: test-deployment
  namespace: test-namespace
spec:
  template:
    metadata:
    spec:
        spec:
          containers:
          - image: {.kubefed.imageRegistry}/nginx:latest
            name: nginx
````

**Why is this needed**:

1. Multi-cloud deployment often need to override some common paramters like "imageRegistry", "clusterName", "region", "zone"，it will be great when we can reference these parameters like valueFrom 
2. although pod's spec have the valueFrom for env, it's not enough yet, we want the "valueFrom" capacity for the whole resource in federation, for example : metadata.labels, metadata.annotations, image, labelselectors, so the probable solution is support valueFrom during overrides

/kind feature
