### ISSUE TITLE
kubefed misses template: field when generating federated crds based on v1 crds

### ISSUE THREAD

**Issue by yalctay93** [kubernetes-sigs/kubefed#1458]
Please help us understand what is going wrong here. Eversince we use the apiVersion v1 of the ```istioOperator``` CRDs, kubefed is not creating the template: field on the ```federatedIstioOperator``` anymore.

I have basically explained the procedure to reproduce this issue here: https://github.com/kubernetes-sigs/kubefed/issues/1418

It looks like for some reason, when kubefed creates a federatedCrd which is a v1 crd, the template: field for that federatedCrd is missing.

I noticed all of that based on the istio operator-crd.yaml (I will post the working v1beta1 crd and the NOT working v1 crd further below - not working means that the template: field will be missing on the federatedCRD when using kubefedctl enable)

Here is the ```federatedIstioOperator``` crd which is based on the v1beta1 ```istiooperator``` crd, which still has the template: field:

```
Name:         federatedistiooperators.types.kubefed.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2021-09-21T15:06:18Z
  Generation:          1
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:conditions:
          k:{"type":"Established"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
          k:{"type":"NamesAccepted"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
    Manager:      kube-apiserver
    Operation:    Update
    Time:         2021-09-21T15:06:18Z
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          .:
          f:strategy:
        f:group:
        f:names:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:scope:
        f:versions:
    Manager:         kubefedctl
    Operation:       Update
    Time:            2021-09-21T15:06:18Z
  Resource Version:  460013
  UID:               d726dae9-1466-4d72-bbf4-08afa9274f62
Spec:
  Conversion:
    Strategy:  None
  Group:       types.kubefed.io
  Names:
    Kind:       FederatedIstioOperator
    List Kind:  FederatedIstioOperatorList
    Plural:     federatedistiooperators
    Short Names:
      fiop
    Singular:  federatedistiooperator
  Scope:       Namespaced
  Versions:
    Name:  v1beta1
    Schema:
      openAPIV3Schema:
        Properties:
          API Version:
            Type:  string
          Kind:
            Type:  string
          Metadata:
            Type:  object
          Spec:
            Properties:
              Overrides:
                Items:
                  Properties:
                    Cluster Name:
                      Type:  string
                    Cluster Overrides:
                      Items:
                        Properties:
                          Op:
                            Pattern:  ^(add|remove|replace)?$
                            Type:     string
                          Path:
                            Type:  string
                          Value:
                            X - Kubernetes - Preserve - Unknown - Fields:  true
                        Required:
                          path
                        Type:  object
                      Type:    array
                  Type:        object
                Type:          array
              Placement:
                Properties:
                  Cluster Selector:
                    Properties:
                      Match Expressions:
                        Items:
                          Properties:
                            Key:
                              Type:  string
                            Operator:
                              Type:  string
                            Values:
                              Items:
                                Type:  string
                              Type:    array
                          Required:
                            key
                            operator
                          Type:  object
                        Type:    array
                      Match Labels:
                        Additional Properties:
                          Type:  string
                        Type:    object
                    Type:        object
                  Clusters:
                    Items:
                      Properties:
                        Name:
                          Type:  string
                      Required:
                        name
                      Type:  object
                    Type:    array
                Type:        object
              Template:
                Type:                                          object
                X - Kubernetes - Preserve - Unknown - Fields:  true
            Type:                                              object
          Status:
            Properties:
              Clusters:
                Items:
                  Properties:
                    Name:
                      Type:  string
                    Remote Status:
                      Type:                                          object
                      X - Kubernetes - Preserve - Unknown - Fields:  true
                    Status:
                      Type:  string
                  Required:
                    name
                  Type:  object
                Type:    array
              Conditions:
                Items:
                  Properties:
                    Last Transition Time:
                      Format:  date-time
                      Type:    string
                    Last Update Time:
                      Format:  date-time
                      Type:    string
                    Reason:
                      Type:  string
                    Status:
                      Type:  string
                    Type:
                      Type:  string
                  Required:
                    type
                    status
                  Type:  object
                Type:    array
              Observed Generation:
                Format:  int64
                Type:    integer
            Type:        object
        Required:
          spec
        Type:  object
    Served:    true
    Storage:   true
    Subresources:
      Status:
Status:
  Accepted Names:
    Kind:       FederatedIstioOperator
    List Kind:  FederatedIstioOperatorList
    Plural:     federatedistiooperators
    Short Names:
      fiop
    Singular:  federatedistiooperator
  Conditions:
    Last Transition Time:  2021-09-21T15:06:18Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2021-09-21T15:06:18Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1beta1
Events:  <none>
```

after we update the ```istiooperator``` crd to the new v1 apiVersion, and execute ```kubefedctl enable istiooperator```, the ```federatedIstioOperator``` looks like this, notice how the template: field is missing now. This leads to our federatedIstioOperator resources to literally not have any  ```spec.template``` configurations, it is completely absent.

```
Name:         federatedistiooperators.types.kubefed.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2021-09-21T15:06:18Z
  Generation:          2
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:conditions:
          k:{"type":"Established"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
          k:{"type":"NamesAccepted"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
    Manager:      kube-apiserver
    Operation:    Update
    Time:         2021-09-21T15:06:18Z
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          .:
          f:strategy:
        f:group:
        f:names:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:scope:
        f:versions:
    Manager:         kubefedctl
    Operation:       Update
    Time:            2021-09-21T15:06:18Z
  Resource Version:  4985554
  UID:               d726dae9-1466-4d72-bbf4-08afa9274f62
Spec:
  Conversion:
    Strategy:  None
  Group:       types.kubefed.io
  Names:
    Kind:       FederatedIstioOperator
    List Kind:  FederatedIstioOperatorList
    Plural:     federatedistiooperators
    Short Names:
      fiop
      fio
    Singular:  federatedistiooperator
  Scope:       Namespaced
  Versions:
    Name:  v1beta1
    Schema:
      openAPIV3Schema:
        Properties:
          API Version:
            Type:  string
          Kind:
            Type:  string
          Metadata:
            Type:  object
          Spec:
            Properties:
              Overrides:
                Items:
                  Properties:
                    Cluster Name:
                      Type:  string
                    Cluster Overrides:
                      Items:
                        Properties:
                          Op:
                            Pattern:  ^(add|remove|replace)?$
                            Type:     string
                          Path:
                            Type:  string
                          Value:
                            X - Kubernetes - Preserve - Unknown - Fields:  true
                        Required:
                          path
                        Type:  object
                      Type:    array
                  Type:        object
                Type:          array
              Placement:
                Properties:
                  Cluster Selector:
                    Properties:
                      Match Expressions:
                        Items:
                          Properties:
                            Key:
                              Type:  string
                            Operator:
                              Type:  string
                            Values:
                              Items:
                                Type:  string
                              Type:    array
                          Required:
                            key
                            operator
                          Type:  object
                        Type:    array
                      Match Labels:
                        Additional Properties:
                          Type:  string
                        Type:    object
                    Type:        object
                  Clusters:
                    Items:
                      Properties:
                        Name:
                          Type:  string
                      Required:
                        name
                      Type:  object
                    Type:    array
                Type:        object
            Type:            object
          Status:
            Properties:
              Clusters:
                Items:
                  Properties:
                    Name:
                      Type:  string
                    Remote Status:
                      Type:                                          object
                      X - Kubernetes - Preserve - Unknown - Fields:  true
                    Status:
                      Type:  string
                  Required:
                    name
                  Type:  object
                Type:    array
              Conditions:
                Items:
                  Properties:
                    Last Transition Time:
                      Format:  date-time
                      Type:    string
                    Last Update Time:
                      Format:  date-time
                      Type:    string
                    Reason:
                      Type:  string
                    Status:
                      Type:  string
                    Type:
                      Type:  string
                  Required:
                    type
                    status
                  Type:  object
                Type:    array
              Observed Generation:
                Format:  int64
                Type:    integer
            Type:        object
        Required:
          spec
        Type:  object
    Served:    true
    Storage:   true
    Subresources:
      Status:
Status:
  Accepted Names:
    Kind:       FederatedIstioOperator
    List Kind:  FederatedIstioOperatorList
    Plural:     federatedistiooperators
    Short Names:
      fiop
      fio
    Singular:  federatedistiooperator
  Conditions:
    Last Transition Time:  2021-09-21T15:06:18Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2021-09-21T15:06:18Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1beta1
Events:  <none>
```

and here are the ```v1beta1``` and ```v1``` ```operator-crd.yamls```, you can try to reproduce it by enabling the ```v1beta1``` and using the ```kubefedctl enable istiooperators``` command. The``` template:``` field should exist on your``` federatedIstioOperator``` crd. Afterwards, delete the ```v1beta1``` CRD and deploy the ```v1``` CRD of ```istiooperators```. If you now execute the ```kubefedctl enable istiooperators``` command again, you will notice that the ```template:``` field is missing in the ```federatedIstioOperator``` crd 

v1beta1:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.install.istio.io
spec:
  group: install.istio.io
  names:
    kind: IstioOperator
    plural: istiooperators
    singular: istiooperator
    shortNames:
    - iop
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        spec:
          description: 'Specification of the desired state of the istio control plane resource.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          type: object
        status:
          description: 'Status describes each of istio control plane component status at the current time.
            0 means NONE, 1 means UPDATING, 2 means HEALTHY, 3 means ERROR, 4 means RECONCILING.
            More info: https://github.com/istio/api/blob/master/operator/v1alpha1/istio.operator.v1alpha1.pb.html &
            https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
```

v1

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.install.istio.io
  labels:
    release: istio
spec:
  conversion:
    strategy: None
  group: install.istio.io
  names:
    kind: IstioOperator
    listKind: IstioOperatorList
    plural: istiooperators
    singular: istiooperator
    shortNames:
    - iop
    - io
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Istio control plane revision
      jsonPath: .spec.revision
      name: Revision
      type: string
    - description: IOP current state
      jsonPath: .status.status
      name: Status
      type: string
    - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
---
```
