### ISSUE TITLE
Allow resource name overriding from spec.template.metadata.name

### ISSUE THREAD

**Issue by cebernardi** [kubernetes-sigs/kubefed#1463]
**What would you like to be added**:
Adding the capability to override the target resource name from `spec.template.metadata.name`

**Why is this needed**:

We are facing a situation where we need to propagate a resource with different fields in all the clusters.

Let's say a Configmap:

```
apiVersion: types.kubefed.io/v1beta1
kind: FederatedConfigMap
metadata:
  name: name-of-configmap
  namespace: default
spec:
  placement:
    clusterSelector: {}
  template:
    data:
      values.yaml: |
        key: value 
```

We want to distribute this configmap to a subset of cluster with `key: another-value`, but we need the resource to be crated in every target cluster with the same name, as it will be used by other services.

The number of clusters doesn't allow us to use the `clusterOverrides` feature as it would be very impractical listing everything, and also the cluster fleet is dynamic, so we can't really leverage this feature.

Currently, the target resource will be named after the FederatedResource, but if we could override the name specifying `spec.template.metadata.name`, we could do:

```
apiVersion: types.kubefed.io/v1beta1
kind: FederatedConfigMap
metadata:
  name: configmap-red-clusters
  namespace: default
spec:
  placement:
    clusterSelector:
      matchLabels:
        color: red
  template:
    data:
      values.yaml: |
        key: value 
   metadata:
      name: name-of-configmap
```
and

```
apiVersion: types.kubefed.io/v1beta1
kind: FederatedConfigMap
metadata:
  name: configmap-green-clusters
  namespace: default
spec:
  placement:
    clusterSelector:
      matchLabels:
        color: gren
  template:
    data:
      values.yaml: |
        key: value 
   metadata:
      name: name-of-configmap
```

The different FederatedConfigmaps (`configmap-red-clusters` and `configmap-green-clusters`) will be propagating a target Configmap with the same name (`name-of-configmap`).

We could achieve the same with this feature request (https://github.com/kubernetes-sigs/kubefed/issues/1462)

/kind feature
