### ISSUE TITLE
KubeFed controller crash when meeting negative array index in overrides 

### ISSUE THREAD

**Issue by zqzten** [kubernetes-sigs/kubefed#1466]
**What happened**:
When we use negative array index in overrides of one federated object as below, KubeFed controller panicked and crashed when reconciling that object.
```yaml
...
spec:
  overrides:
  - clusterName: foo
    clusterOverrides:
    - op: replace
      path: /spec/somearray/-1
      value: bar
...
```

**What you expected to happen**:
KubeFed controller applies that override correctly as evanphx/json-patch#123 does.

/kind bug
