### ISSUE TITLE
clusterOverrides for multiple annotations syntax

### ISSUE THREAD

**Issue by yalctay93** [kubernetes-sigs/kubefed#1478]
Hello, my question is how can  I override multiple annotations with clusterOverrides?
the below example works for one annotation:

```
    clusterOverrides:
    - path: /spec/loadBalancerIP
      value: x.x.x.x
    - op: add
      path: /metadata/annotations
      value:
        loadbalancer.openstack.org/class: internet
```

But for two annotations, how does the syntax look like? I tried this but it is not working;
```
    clusterOverrides:
    - path: /spec/loadBalancerIP
      value: x.x.x.x
    - op: add
      path: /metadata/annotations
      value:
        loadbalancer.openstack.org/class: internet
    - op: add
      path: /metadata/annotations
      value:
        secondannotation: test
```

/triage support
