### ISSUE TITLE
Should the KubeFed synchronization controller overwrite the modification of the pvc spec field by the member cluster?

### ISSUE THREAD

**Issue by 0xff-dev** [kubernetes-sigs/kubefed#1481]
**What happened**:
In my cluster, I create the resource `FederatedPersistentVolumeClaims`, and then create a `cr` of `fpvc`. When the pv in the member cluster is bound to pvc, the `volumeName` field of pvc will be modified, but the kubefed controller will issue an error at this time.
```shell
Warning   UpdateInClusterFailed   federatedpersistentvolumeclaim/test1234   Failed to update PersistentVolumeClaim "test1234/test1234" in cluster "585ae638bd68": PersistentVolumeClaim "test1234" is invalid: spec: Forbidden: s
pec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
            AccessModes:      {"ReadWriteMany"},
            Selector:         nil,
            Resources:        {Requests: {s"storage": {i: {...}, Format: "BinarySI"}}},
-           VolumeName:       "",
+           VolumeName:       "pvc-a18b6f21-527d-452b-8570-684d8bf066ff",
            StorageClassName: &"ha-nfs",
            VolumeMode:       &"Filesystem",
            DataSource:       nil,
  }

```

But in the end, the controller did not change this field back.
```shell
pvc-examples # kubectl get pvc test1234 -ntest1234
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test1234   Bound    pvc-a18b6f21-527d-452b-8570-684d8bf066ff   512Mi      RWX            ha-nfs         6m1s
```

**What you expected to happen**:
Maybe there shouldn't be a warning log. 
Perhaps should add a description here[Local Value Retention](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#local-value-retention), or whether  can provide a check to skip some fields.

**How to reproduce it (as minimally and precisely as possible)**:
example yaml
```yaml
apiVersion: types.kubefed.io/v1beta1
kind: FederatedPersistentVolumeClaim
metadata:
  name: test1234
  namespace: test1234
spec:
  overrides:
  - clusterName: 585ae638bd68
    clusterOverrides:
    - path: /spec/storageClassName
      value: ha-nfs
  - clusterName: 157092d9799e
    clusterOverrides:
    - path: /spec/storageClassName
      value: nfs-fata
  placement:
    clusters:
    - name: 585ae638bd68
    - name: 157092d9799e
  template:
    metadata:
      labels:
        system/srType: share
        system/storageType: nfs
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 512Mi
```
**Anything else we need to know?**:
kubefed : v0.2.0-alpha.1. Haven't used the latest kubefed yet.

**Environment**:
- Kubernetes version (use `kubectl version`)
1.20.8

- KubeFed version
v0.2.0-alpha.1

- Scope of installation (namespaced or cluster)
namespaced (kube-federation-system)
- Others

/kind bug
