### ISSUE TITLE
Cannot use DownwardAPI on FederatedDeployment

### ISSUE THREAD

**Issue by mvazquezc** [kubernetes-sigs/kubefed#509]
Given a deployment with a DownwardAPI volume:

```
<output ommited>
              volumeMounts:
              - mountPath: /var/tmp/podinfo
                name: pod-info
            volumes:
            - name: pod-info
              downwardAPI:
                items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
<output ommited>
```

When creating the FederatedDeployment object it fails as per validation failure:

validation failure list:
type in spec.template.spec.template.spec.volumes.downwardAPI is required

This was working on v0.0.3, now we're on Canary.
