### ISSUE TITLE
improve doc on kubefed2 join - what happens behind the scene

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/kubefed#613]
**What would you like to be added**: 

Documentation about what happens exactly on when a kubefed join command is issued.

**Why is this needed**: 

The imperative nature of the kubefed2 CLI may be a limitation for fully declarative environment. Knowing what it is supposed to happen in a kubefed2 join, would allow to create a more declarative operator to manage cluster joining and leaving a federation.

/kind feature

**Comment by marun** [comment]
The join operation creates a namespace, service account, and rbac roles and bindings in a cluster targeted for federation membership.  How would a declarative operator acquire the privileged cluster credentials necessary to perform these operations on an arbitrary cluster?

**Comment by raffaelespazzoli** [comment]
@marun I am thinking of using this kind of API structure:

```
Kind: KubernetesFederation
metadata:
name: myfederaton
spec:
 clusters:
 # this refers to a cluster in the cluster registry
 - clusterRef: cluster1
 # this is a reference to a secret containing a kubeconfig that allows access to the cluster. 
   secretRef: cluster1-kubeconfig
 - clusterRef: cluster2
    secretRef: cluster2-kubeconfig
```
As you can see from the comments I assume that the credentials exist as secret.
