### ISSUE TITLE
Support resource grouping

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#774]
Currently federation only manages individual resources.  There is no mechanism to define the relationship between the resources that comprise an application (e.g. a service that depends on a deployment that depends on a secret).  This complicates scheduling, which only knows about scalable resources but not its dependents or dependencies.  It also prevents the reporting of the sync status of the resources that comprise an application.    

/kind feature

**Comment by TwinProduction** [comment]
This is definitely something that would be necessary long term.

For instance, think deploying a resource containing a CRD, and then federating a separate resource using said CRD.

In a perfect world, we'd be able to set `dependencies` at either the target cluster, or at the kubefed cluster level, though the latter may be simpler to implement.

## At the target cluster level
The idea would be that a federated resource would not be pushed to a cluster unless said cluster has the specified resource.
```yaml
dependencies:
  inTargetCluster:
    - kind: Deployment
      namespace: kube-system
      name: cert-manager
```
where the `namespace` is optional so that we may support non-namespaced resources like CRDs

## At the kubefed cluster level
Unlike the former, this configuration would enable a federated resource to wait until another federated resource has been successfully federated in a particular target cluster _before_ federating it to said particular the target cluster.
```yaml
dependencies:
  inKubefedCluster:
    - kind: FederatedDeployment
      namespace: kube-system
      name: cert-manager
```

/reopen
/remove-lifecycle rotten
