### ISSUE TITLE
Ability to disable leader election

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kubefed#798]
In order to properly debug the `controller-manager` using a debugger, it is necessary to be able to disable leader election. Otherwise while things are halted in the debugger, the leader election will timeout resulting in an unusable debug session. Adjusting the various leader election time interval options that are currently available and shown below is not sufficient. As while it may improve the ability to halt the execution without leader election timing out, it delays the initial startup of the program while leader election is being performed.

```yaml
  leader-elect:
    lease-duration: 15s
    renew-deadline: 10s
    resource-lock: configmaps
    retry-period: 5s
```

/kind feature
