### ISSUE TITLE
clusterSelector is ignored with ReplicaSchedulingPreference

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/kubefed#981]
Following FederatedDeployment schedules correctly only to clusters with label `region=eu-west1`

```
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedDeployment
metadata:
  name: nginx
  namespace: testing
spec:
  placement:
    clusterSelector:
      matchLabels:
        region: eu-west1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 5
      terminationGracePeriodSeconds: 0
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: nginx
            name: nginx
```

When I add RSP to limit the maximum replicas it schedules to all clusters, ignoring the label:
```
apiVersion: scheduling.kubefed.k8s.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: nginx
  namespace: testing
spec:
  targetKind: FederatedDeployment
  totalReplicas: 15
  clusters:
    "*":
      maxReplicas: 3
      weight: 1
```

**Comment by marun** [comment]
This behavior is by design.  When RSP is enabled, placement is the result of the scheduling decision and that decision is applied via the `spec.placement.clusters` field. As per the following documentation, `clusterSelector` is ignored if `clusters` is provided:

https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#both-specplacementclusters-and-specplacementclusterselector-are-provided

Are you wanting RSP to support a selector for determining weights?

**Comment by matti** [comment]
I want to limit `maxReplicas` in every cluster. the `weight` is not relevant.

My usecase: run 1000 replicas in n clusters (not specified up front), but only max 100 in one cluster. So if federation has only 1 clusters, only 100 will be running until another cluster is added, and then there are 200 replicas.

I want to use cluster labels to only run replicas with a subset of the clusters.

**Comment by marun** [comment]
I think it would be helpful to hear more about what use case is involved here.  I'm not sure what you've described thus far represents a real-world scenario that other stakeholders would identify with.

cc: @irfanurrehman

**Comment by matti** [comment]
Well, I can only describe my real world scenario. I'm currently running my workloads in ~20 GKE clusters that are in one or more regions at the same time. I've built my own "federation". The reason why I run multiple GKE clusters is that I need to scale quicker than that - One cluster can scale approx 10 replicas / second and I need to scale the total number of replicas faster than that. So my current solution is to run scale in different clusters at the same time. For example, with 3 clusters I get approx 30 replicas / second..

So currently the use case described above works with federation v2.  What doesn't work is when I have federated 3 clusters from europe-west4 and 3 clusters from us-east1 --> replicas are created in two regions and I'd like to use `clusterSelector` to use only europe-west4.

I can workaround this by specifying more detailed `cluster:` fields in RSP, but I'd rather keep RSP as simple and use it to limit the maximum number of replicas per cluster. 

Using labels would be ideal for this,.

**Comment by matti** [comment]
I would imagine some "other stakeholder" to use similar pattern to run web apps in a subset of federated clusters so that when `totalReplicas: 15` is specified and a cluster leaves the federation (maintenance, upgrade, etc) the stakeholder wants to limit scheduling all replicas in remaining cluster(s) (potentially ddossing the cluster).

**Comment by matti** [comment]
If `clusterSelector` is ignored when `cluster:` is defined - could it be that `totalReplicas` is under wrong key? `cluster:` is clearly meant for using fixed, named clusters as targets for replicas, while `totalReplicas` is a higher level concept.

It has to be possible to have `totalReplicas` with `clusterSelector` - it just makes sense to have these defined at the same time.

**Comment by irfanurrehman** [comment]
@matti would you be willing to present your case in todays or next weeks federation sync [Wednesdays at 7:30 PT](https://github.com/kubernetes/community/tree/master/sig-multicluster) to get an opinion of rest of the folks. Implementation to include this case is not difficult, but there should be general consensus that this represents a wider usage.

**Comment by matti** [comment]
@irfanurrehman sure, how do I join that?

**Comment by irfanurrehman** [comment]
https://zoom.us/my/k8s.mc

**Comment by matti** [comment]
@irfanurrehman added this as agenda proposal comment to https://docs.google.com/document/d/1v-Kb1pUs3ww_x0MiKtgcyTXCAuZlbVlz4_A9wS3_HXY/edit#heading=h.9t4iuhw7ni0u

My time is a bit limited, I can be present ~7:30-8:00

**Comment by irfanurrehman** [comment]
> @irfanurrehman added this as agenda proposal comment to https://docs.google.com/document/d/1v-Kb1pUs3ww_x0MiKtgcyTXCAuZlbVlz4_A9wS3_HXY/edit#heading=h.9t4iuhw7ni0u
> 
> My time is a bit limited, I can be present ~7:30-8:00

Thanks @matti, that should be fine.

**Comment by xunpan** [comment]
/assign
let me follow up this ticket

**Comment by xunpan** [comment]
From my point of view, 
`placement` of `FederatedDeployment` is used to assign the resource placement.
`ReplicaSchedulingPreference` is used to control replicas for resources allocated to each cluster. It does not need to control the resource placement. We do not need to duplicate placement function in `Federated*` resources.

 @matti @irfanurrehman any comments?

**Comment by irfanurrehman** [comment]
@xunpan I think the scenario @matti asked for is genuine. What he is asking for is being able to combine the label based placement with the replica scheduling preference. Design wise, I think it can be built in the RSP scheduler to additionally consider the label selector in its decisions.

**Comment by xunpan** [comment]
I think we want below case
```
apiVersion: scheduling.kubefed.k8s.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: nginx
  namespace: testing
spec:
  targetKind: FederatedDeployment
  totalReplicas: 15
    clusterSelector:
      - matchLabels:
          foo: bar
        maxReplicas: 3
        weight: 1
      - matchLabels:
          foo: foo
        maxReplicas: 5
        weight: 2
```
